export const TYPE_BG_CLASS_MAP = {
  bug: "bg-type-bug",
  dark: "bg-type-dark",
  dragon: "bg-type-dragon",
  electric: "bg-type-electric",
  fairy: "bg-type-fairy",
  fighting: "bg-type-fighting",
  fire: "bg-type-fire",
  flying: "bg-type-flying",
  ghost: "bg-type-ghost",
  normal: "bg-type-normal",
  grass: "bg-type-grass",
  ground: "bg-type-ground",
  ice: "bg-type-ice",
  poison: "bg-type-poison",
  psychic: "bg-type-psychic",
  rock: "bg-type-rock",
  steel: "bg-type-steel",
  water: "bg-type-water",
} as const;

export const TYPE_BG_OPACITY_MAP = {
  bug: "bg-type-bug/20",
  dark: "bg-type-dark/20",
  dragon: "bg-type-dragon/20",
  electric: "bg-type-electric/20",
  fairy: "bg-type-fairy/20",
  fighting: "bg-type-fighting/20",
  fire: "bg-type-fire/20",
  flying: "bg-type-flying/20",
  ghost: "bg-type-ghost/20",
  normal: "bg-type-normal/20",
  grass: "bg-type-grass/20",
  ground: "bg-type-ground/20",
  ice: "bg-type-ice/20",
  poison: "bg-type-poison/20",
  psychic: "bg-type-psychic/20",
  rock: "bg-type-rock/20",
  steel: "bg-type-steel/20",
  water: "bg-type-water/20",
} as const;

export const TYPE_TEXT_COLOR_CLASS_MAP = {
  bug: "text-type-bug",
  dark: "text-type-dark",
  dragon: "text-type-dragon",
  electric: "text-type-electric",
  fairy: "text-type-fairy",
  fighting: "text-type-fighting",
  fire: "text-type-fire",
  flying: "text-type-flying",
  ghost: "text-type-ghost",
  normal: "text-type-normal",
  grass: "text-type-grass",
  ground: "text-type-ground",
  ice: "text-type-ice",
  poison: "text-type-poison",
  psychic: "text-type-psychic",
  rock: "text-type-rock",
  steel: "text-type-steel",
  water: "text-type-water",
} as const;
